debug: false
bot:
    name: "Random Bets Bot"
    version: "0.1"

api:
    twitch_client_id: idhere
    twitch_client_secret: secrethere

credentials:
    # http://twitchapps.com/tmi)
    irc: oauth:tokenhere

# Channels - The bot will connect to all listed channels
channels:
    - channelhere